# Parameters used to generate this project with aem-project-archetype

groupId=com.vasscompany
artifactId=vass-university-dummyproject
version=1.0-SNAPSHOT
package=com.vasscompany.dummyproject
appId=vass-university-dummyproject
appTitle=VASS.University.dummyproject
aemVersion=6.5.8
sdkVersion=latest
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=none
singleCountry=y
includeDispatcherConfig=n
includeCif=n
includeForms=n
includeFormsenrollment=n
includeFormscommunications=n
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=y
amp=n
enableDynamicMedia=n
enableSSR=n
precompiledScripts=n
includeFormsheadless=n
uiTestingFramework=cypress
